name: samsunghealth
description: A new Flutter plugin.
version: 0.0.2
author:
homepage: https://github.com/mondoktamas/flutter_samsunghealth.git

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


#flutter:
#  plugin:
#    platforms:
#      android:
#        androidPackage: com.flutter.samsunghealth
#        pluginClass: SamsunghealthPlugin


flutter:
  plugin:
    androidPackage: com.flutter.samsunghealth
    pluginClass: SamsunghealthPlugin
